### ISSUE TITLE
Mobile - Firefox issue

### ISSUE THREAD

**Issue by vahan1107** [eyeson-team/js-docs#44] opened 2023-06-15 11:56 UTC
Hi!
Device and browser info:
Redmi Note 11 Pro 5G with Android 12 and MIUI Global v13.0.6 - Firefox 114.1.0

The problem is that other users can't hear and see user of this device. And also Redmi user can hear voices of other users but can see them.
 
Thanks in advance

**Comment by opusonline** [comment] 2023-06-16 08:19
Hi!
Thanks for your feedback!

We're constantly running tests on different devices and operating systems. We've also checked Firefox on an Android 12 mobile device and we couldn't find any issue, it's all working as expected.

Have you tried with different networks? Is it working on other Android devices in the same network? Have you tried using the eyeson GUI on this device? How about installing the [eyeson Android app](https://play.google.com/store/apps/details?id=eyeson.visocon.at.eyesonteam), are there also mic and cam issues? Is the Chrome remote debugging tool giving more inormation?

Thanks for your help!

Best regards, Stefan

**Comment by vahan1107** [comment] 2023-06-16 12:23
Hi Stefan.

Thank you! 
1. There is no issue connected with a networks.
2. Checked also on a Samsung (other Android device), works fine.
3. Checked using eyeson GUI with problematic device, works fine.
4. Installed eyeson Android app, checked, when trying to use it I can see myself in the background video and can't join to the meeting. Note: it didn't show me any error or warning (including mic and cam info).
5. We have a problem on the Firefox only so I can't use the chrome remote debugging tool). BTW the problematic mobile device has no any issue when using Chrome browser.
6. We have tested in this page [eyeson quick test](https://app.eyeson.team/quicktest/) page, we got this warning only:
```
Check microphone
Microphone input level is low, increase it
Input volume or get close to the microphone. Is there a mute switch on your device?
```

Let me check my codes carefully again.
A strange thing is that I have a problem on Redmi cellphones on Firefox only (FYI: but not on all models). If you have any suggestion what I can miss or what I can wrote something in my codes will be great.

Thank you!

**Comment by opusonline** [comment] 2023-06-16 13:59
Hi @vahan1107 
Thank you so much for running all the checks! That's very helpful!

Now this tells me that the device is working properly, but there must be an issue in your implementation.
I would love to help, but therefor I would need the code and maybe also the test device.

By the way, there's also a remote debugging tool in Firefox. [See this instruction](https://hacks.mozilla.org/2012/08/remote-debugging-on-firefox-for-android/).

I will close this ticket for now, because there's no explicit issue with the web-sdk itself since it works properly in the eyeson GUI and I can't reproduce your issue on Android in general. And unfortunately I don't have any suggestions for what's missing, because I never had this issue.

As far as I know, our support is already in contact with you, so we can proceed this way if needed.

If you have any more feedback on that issue, you can still add comments to this ticket.

Best regards, Stefan

**Closed by opusonline** 2023-06-16 13:59 UTC
